/**
 * @file main.cpp
 * @author Lucas Camargo da Silva (lucas.camargodasilva@hotmail.com)
 * @brief Program that reads a log file containing data generated by
 * an accelerometer and produces an output file with the corresponding
 * attitude estimation.
 * @version 1.0.0
 * @date 2022-09-27
 * 
 * @copyright Copyright (c) 2022
 * 
 */

#include <iostream>
#include <string>
#include "attitude-estimation.h"
#include "accelerometer-data.h"
#include "attitude-estimator.h"

/**
 * @brief Read a log file containing data generated by an accelerometer
 * and produce an output file with the corresponding attitude estimation.
 * 
 * @param argv[0] Accelerometer data file path
 * @param argv[1] Desired attitude estimation data file path
 */
int main(int argc, char *argv[]) {
    // Read input paths for the accelerometer data file and the desired attitude estimation data file
    std::string accelerometerDataFilePath = argv[1], attitudeEstimationDataFilePath = argv[2];

    // Read accelerometer data from the accelerometer data file
    AccelerometerData accelerometerData = AccelerometerData(accelerometerDataFilePath);

    // Generate vector of attitude estimations from the read accelerometer data
    AttitudeEstimator attitudeEstimator = AttitudeEstimator(accelerometerData.getAccelerometerData());

    // Write file containing the calculated attitude estimations
    writeAttitudeEstimationFile(attitudeEstimator.getAttitudeEstimation(), attitudeEstimationDataFilePath);
}